# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ports < Formula
  desc "Beautiful CLI to list, check and kill running ports"
  homepage "https://github.com/acousticclown/ports"
  version "0.1.5"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/acousticclown/ports/releases/download/v0.1.5/ports_0.1.5_darwin_amd64.tar.gz"
      sha256 "640bd7a06e5fbd0dd2437df22123f45c7d0c1163bd7cefd98681d2063d16f55c"

      def install
        bin.install "ports"
      end
    end
    on_arm do
      url "https://github.com/acousticclown/ports/releases/download/v0.1.5/ports_0.1.5_darwin_arm64.tar.gz"
      sha256 "5378ff308f1e25d60b184b902356d36b06351da3022daf053a69457a20b3b236"

      def install
        bin.install "ports"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/acousticclown/ports/releases/download/v0.1.5/ports_0.1.5_linux_amd64.tar.gz"
        sha256 "d278dc781f16fdd39af7836029763930cf39b234f291a9416cfec3de6d583017"

        def install
          bin.install "ports"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/acousticclown/ports/releases/download/v0.1.5/ports_0.1.5_linux_arm64.tar.gz"
        sha256 "8d71ec070000def5ae8fdc0e445075d8797a16ca3b9325db13c8e1ea34c6b42e"

        def install
          bin.install "ports"
        end
      end
    end
  end
end
