# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ports < Formula
  desc "Beautiful CLI to list, check and kill running ports"
  homepage "https://github.com/acousticclown/ports"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/acousticclown/ports/releases/download/v0.1.1/ports_0.1.1_darwin_amd64.tar.gz"
      sha256 "788fc97d6d7c55660ae2a44404eba548bb0f76714552668fcce78946ed8f6b56"

      def install
        bin.install "ports"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/acousticclown/ports/releases/download/v0.1.1/ports_0.1.1_darwin_arm64.tar.gz"
      sha256 "5b29ec99ca81284c3520e9b602fb457b50c0e1632e98e7081c24794b3d1060c0"

      def install
        bin.install "ports"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/acousticclown/ports/releases/download/v0.1.1/ports_0.1.1_linux_amd64.tar.gz"
      sha256 "7d6169d2b996c9f767009eff961d1b38803dd89c429969dde122cc006e3b1cd4"
      def install
        bin.install "ports"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/acousticclown/ports/releases/download/v0.1.1/ports_0.1.1_linux_arm64.tar.gz"
      sha256 "e97539b661fd0fce9e648b7bfd39809fed3adf8e022d3829bc852a8db7b38661"
      def install
        bin.install "ports"
      end
    end
  end
end
