# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ports < Formula
  desc "Beautiful CLI to list, check and kill running ports"
  homepage "https://github.com/acousticclown/ports"
  version "0.1.6"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/acousticclown/ports/releases/download/v0.1.6/ports_0.1.6_darwin_amd64.tar.gz"
      sha256 "7e6e4800ee4cd2ff77218024a46452fa1472c0a9f221cff76ecbf82f7663a960"

      def install
        bin.install "ports"
      end
    end
    on_arm do
      url "https://github.com/acousticclown/ports/releases/download/v0.1.6/ports_0.1.6_darwin_arm64.tar.gz"
      sha256 "757df5a26b1ff1aa55c9766f13970209018cde5d54930f357079e759ad724085"

      def install
        bin.install "ports"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/acousticclown/ports/releases/download/v0.1.6/ports_0.1.6_linux_amd64.tar.gz"
        sha256 "99301fb90ccaf5f55e289d6c2052adabe04f1d06c5d543ebbf90be0f41bfe664"

        def install
          bin.install "ports"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/acousticclown/ports/releases/download/v0.1.6/ports_0.1.6_linux_arm64.tar.gz"
        sha256 "9de02449f57e4af13e0c62c6ef9fcbf4a4e343799e564678d442e1be3e521615"

        def install
          bin.install "ports"
        end
      end
    end
  end
end
