# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ports < Formula
  desc "Beautiful CLI to list, check and kill running ports"
  homepage "https://github.com/acousticclown/ports"
  version "1.0.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/acousticclown/ports/releases/download/v1.0.0/ports_1.0.0_darwin_amd64.tar.gz"
      sha256 "f72f36a2e8d398ac2ec0fe8ce94981daa26f1cfa78246fb93a609c98d6ac648e"

      def install
        bin.install "ports"
      end
    end
    on_arm do
      url "https://github.com/acousticclown/ports/releases/download/v1.0.0/ports_1.0.0_darwin_arm64.tar.gz"
      sha256 "9fbbe3c48735f96a893c6f59723780d0f30ce77ea36fc5f24ec23e9ba389e7bd"

      def install
        bin.install "ports"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/acousticclown/ports/releases/download/v1.0.0/ports_1.0.0_linux_amd64.tar.gz"
        sha256 "dba171d95d73f7fd081544073340ac150ef42ea0e51dc12abb3981e3f82f0485"

        def install
          bin.install "ports"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/acousticclown/ports/releases/download/v1.0.0/ports_1.0.0_linux_arm64.tar.gz"
        sha256 "e9b06ffbc9c4f34d6533e83a4f0f33f8112ad4348ce4df2ffadd376f5e1f7205"

        def install
          bin.install "ports"
        end
      end
    end
  end
end
