# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ports < Formula
  desc "Beautiful CLI to list, check and kill running ports"
  homepage "https://github.com/acousticclown/ports"
  version "0.1.7"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/acousticclown/ports/releases/download/v0.1.7/ports_0.1.7_darwin_amd64.tar.gz"
      sha256 "de13eabf8280e04efb57586923dfd2006c2249fbd5157e7d4fbe6081b445bcec"

      def install
        bin.install "ports"
      end
    end
    on_arm do
      url "https://github.com/acousticclown/ports/releases/download/v0.1.7/ports_0.1.7_darwin_arm64.tar.gz"
      sha256 "bb725ecce48a71f8dfe7327aa99250bd649e370b963945392d83e99754c6e7d7"

      def install
        bin.install "ports"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/acousticclown/ports/releases/download/v0.1.7/ports_0.1.7_linux_amd64.tar.gz"
        sha256 "51a30458e92a6bd7bab74fb1c89cbb0e2ec6a66ddb6783884ef537351afe8806"

        def install
          bin.install "ports"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/acousticclown/ports/releases/download/v0.1.7/ports_0.1.7_linux_arm64.tar.gz"
        sha256 "4d14b5c3dbf0840501c24fe35641092012e5f86f7d32a30310de4c04d37ae0f2"

        def install
          bin.install "ports"
        end
      end
    end
  end
end
